apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  labels:
    app: keycloak
  name: sigstore
  namespace: keycloak-system
spec:
  realm:
    id: sigstore
    realm: sigstore
    enabled: true
    displayName: sigstore
  instanceSelector:
    matchLabels:
      app: keycloak
