apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: sigstore
  namespace: keycloak-system
  labels:
    app: keycloak
spec:
  user:
    username: "sigstore"
    firstName: "Sigstore"
    lastName: "User"
    enabled: True
    emailVerified: True
    email: "sigstore@redhat.com"
    credentials:
      - type: "password"
        value: "redhat"
  realmSelector:
    matchLabels:
      app: keycloak