{{- range $configKey, $config := .Values.configs }}
{{- if $config.rolebindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.rbac.clusterrole }}
  namespace: {{ $config.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.rbac.clusterrole }}
subjects:
{{- range $rolebinding := $config.rolebindings }}
- kind: ServiceAccount
  name: {{ $rolebinding }}
  namespace: {{ $config.namespace }}
{{- end }}
{{- end }}
{{- end }}